checks:
    php: true
    javascript: true
filter:
    paths:
        - "css/privatebin.css"
        - "css/bootstrap/privatebin.css"
        - "js/privatebin.js"
        - "lib/*.php"
        - "index.php"
coding_style:
    php:
        spaces:
            around_operators:
                additive: false
                concatenation: true
build:
    environment:
        php:
            version: 8.2
    tests:
        override:
            -   command: 'composer require google/cloud-storage && cd tst && XDEBUG_MODE=coverage ../vendor/bin/phpunit'
                coverage:
                    file: 'tst/log/coverage-clover.xml'
                    format: 'clover'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
