<?php declare(strict_types=1);
/**
 * PrivateBin Installation Script
 *
 * Guides through initial setup: database configuration, admin account creation,
 * and generates the conf.php configuration file.
 *
 * IMPORTANT: Delete this file after installation is complete!
 *
 * @link      https://github.com/PrivateBin/PrivateBin
 * @copyright 2012 Sébastien SAUVAGE (sebsauvage.net)
 * @license   https://www.opensource.org/licenses/zlib-license.php The zlib/libpng License
 */

// prevent running if already configured
$configFile = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'cfg' . DIRECTORY_SEPARATOR . 'conf.php';
if (is_readable($configFile)) {
    $existingConfig = parse_ini_file($configFile, true);
    if ($existingConfig && isset($existingConfig['main'])) {
        die('<!DOCTYPE html><html><body><h1>Already Installed</h1><p>PrivateBin is already configured. Delete the entire <code>install/</code> folder for security.</p></body></html>');
    }
}

$error   = '';
$success = false;
$step    = isset($_POST['step']) ? (int) $_POST['step'] : 1;

// process form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($step) {
        case 2:
            // test database connection and generate config
            $dbType    = $_POST['db_type'] ?? 'sqlite';
            $dbHost    = trim($_POST['db_host'] ?? '');
            $dbPort    = trim($_POST['db_port'] ?? '');
            $dbName    = trim($_POST['db_name'] ?? '');
            $dbUser    = trim($_POST['db_user'] ?? '');
            $dbPass    = $_POST['db_pass'] ?? '';
            $tblPrefix = trim($_POST['tbl_prefix'] ?? '');

            $siteName  = trim($_POST['site_name'] ?? 'PrivateBin');
            $authEnabled      = !empty($_POST['auth_enabled']);
            $requireCreate    = !empty($_POST['require_login_create']);
            $requireRead      = !empty($_POST['require_login_read']);
            $allowRegistration = !empty($_POST['allow_registration']);

            $adminUser = trim($_POST['admin_username'] ?? '');
            $adminPass = $_POST['admin_password'] ?? '';
            $adminPass2 = $_POST['admin_password2'] ?? '';

            // build DSN
            $dsn = '';
            switch ($dbType) {
                case 'sqlite':
                    $dataDir = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'data';
                    if (!is_dir($dataDir)) {
                        mkdir($dataDir, 0700, true);
                    }
                    $dsn = 'sqlite:' . $dataDir . DIRECTORY_SEPARATOR . 'db.sq3';
                    $dbUser = null;
                    $dbPass = null;
                    break;
                case 'mysql':
                    $port = $dbPort ?: '3306';
                    $dsn  = "mysql:host={$dbHost};port={$port};dbname={$dbName};charset=UTF8";
                    break;
                case 'pgsql':
                    $port = $dbPort ?: '5432';
                    $dsn  = "pgsql:host={$dbHost};port={$port};dbname={$dbName}";
                    break;
            }

            // test connection
            try {
                $opts = array(
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                );
                if ($dbType === 'mysql' && defined('PDO::MYSQL_ATTR_INIT_COMMAND')) {
                    $opts[PDO::MYSQL_ATTR_INIT_COMMAND] = "SET SESSION sql_mode='ANSI_QUOTES'";
                }
                $pdo = new PDO($dsn, $dbUser, $dbPass, $opts);
            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
                $step  = 1;
                break;
            }

            // validate admin credentials if auth is enabled
            if ($authEnabled) {
                if (empty($adminUser) || strlen($adminUser) < 3) {
                    $error = 'Admin username must be at least 3 characters.';
                    $step  = 1;
                    break;
                }
                if (!preg_match('/^[a-zA-Z0-9_\-\.]{3,64}$/', $adminUser)) {
                    $error = 'Admin username can only contain letters, numbers, underscore, dash, and dot.';
                    $step  = 1;
                    break;
                }
                if (strlen($adminPass) < 8) {
                    $error = 'Admin password must be at least 8 characters.';
                    $step  = 1;
                    break;
                }
                if ($adminPass !== $adminPass2) {
                    $error = 'Passwords do not match.';
                    $step  = 1;
                    break;
                }
            }

            // generate configuration file
            $conf = ";<?php http_response_code(403); /*\n";
            $conf .= "; config file for PrivateBin\n";
            $conf .= "; generated by install.php on " . date('Y-m-d H:i:s') . "\n\n";

            $conf .= "[main]\n";
            $conf .= "name = \"" . addslashes($siteName) . "\"\n";
            $conf .= "discussion = true\n";
            $conf .= "opendiscussion = false\n";
            $conf .= "password = true\n";
            $conf .= "fileupload = false\n";
            $conf .= "burnafterreadingselected = false\n";
            $conf .= "defaultformatter = \"plaintext\"\n";
            $conf .= "sizelimit = 10000000\n";
            $conf .= "template = \"bootstrap5\"\n";
            $conf .= "languageselection = true\n\n";

            $conf .= "[auth]\n";
            $conf .= "enabled = " . ($authEnabled ? 'true' : 'false') . "\n";
            $conf .= "require_login_to_create = " . ($requireCreate ? 'true' : 'false') . "\n";
            $conf .= "require_login_to_read = " . ($requireRead ? 'true' : 'false') . "\n";
            $conf .= "allow_registration = " . ($allowRegistration ? 'true' : 'false') . "\n";
            $conf .= "session_timeout = 3600\n\n";

            $conf .= "[expire]\n";
            $conf .= "default = \"1week\"\n\n";

            $conf .= "[expire_options]\n";
            $conf .= "5min = 300\n";
            $conf .= "10min = 600\n";
            $conf .= "1hour = 3600\n";
            $conf .= "1day = 86400\n";
            $conf .= "1week = 604800\n";
            $conf .= "1month = 2592000\n";
            $conf .= "1year = 31536000\n";
            $conf .= "never = 0\n\n";

            $conf .= "[formatter_options]\n";
            $conf .= "plaintext = \"Plain Text\"\n";
            $conf .= "syntaxhighlighting = \"Source Code\"\n";
            $conf .= "markdown = \"Markdown\"\n\n";

            $conf .= "[traffic]\n";
            $conf .= "limit = 10\n\n";

            $conf .= "[purge]\n";
            $conf .= "limit = 300\n";
            $conf .= "batchsize = 10\n\n";

            $conf .= "[model]\n";
            $conf .= "class = \"Database\"\n\n";

            $conf .= "[model_options]\n";
            $conf .= "dsn = \"" . addslashes($dsn) . "\"\n";
            $conf .= "tbl = \"" . addslashes($tblPrefix) . "\"\n";
            $conf .= "usr = \"" . addslashes($dbUser ?? '') . "\"\n";
            $conf .= "pwd = \"" . addslashes($dbPass ?? '') . "\"\n";
            $conf .= "opt[12] = true\n";

            // write configuration
            $cfgDir = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'cfg';
            if (!is_dir($cfgDir)) {
                mkdir($cfgDir, 0750, true);
            }
            if (!is_writable($cfgDir)) {
                $error = 'Cannot write to cfg/ directory. Please check permissions.';
                $step  = 1;
                break;
            }

            if (file_put_contents($configFile, $conf) === false) {
                $error = 'Failed to write configuration file.';
                $step  = 1;
                break;
            }

            // now bootstrap PrivateBin to create the database tables and admin user
            define('PATH', dirname(__DIR__) . DIRECTORY_SEPARATOR);
            define('PUBLIC_PATH', dirname(__DIR__) . DIRECTORY_SEPARATOR);
            require PATH . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

            try {
                $configuration = new PrivateBin\Configuration();
                $model         = new PrivateBin\Model($configuration);
                $store         = $model->getStore();

                // create admin user if auth is enabled
                if ($authEnabled && !empty($adminUser)) {
                    $auth = new PrivateBin\Auth\Auth($configuration, $store);
                    $result = $auth->createUser($adminUser, $adminPass, PrivateBin\Auth\User::ROLE_ADMIN);
                    if (!$result['success']) {
                        $error = 'Configuration saved but admin creation failed: ' . $result['message'];
                        $step  = 1;
                        break;
                    }
                }
            } catch (Exception $e) {
                $error = 'Configuration saved but database initialization failed: ' . $e->getMessage();
                $step  = 1;
                break;
            }

            $success = true;
            break;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PrivateBin Installation</title>
    <link rel="stylesheet" href="../css/bootstrap-5.3.8.css">
    <style>
        body { background-color: #f8f9fa; }
        .install-container { max-width: 640px; margin: 40px auto; }
        .form-section { background: white; border-radius: 8px; padding: 2rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
        .form-section h5 { margin-bottom: 1rem; border-bottom: 1px solid #eee; padding-bottom: 0.5rem; }
    </style>
</head>
<body>
<div class="install-container">
    <h2 class="mb-4 text-center">🔒 PrivateBin Installation</h2>

<?php if ($success): ?>
    <div class="form-section">
        <div class="alert alert-success">
            <h5 class="alert-heading">✅ Installation Complete!</h5>
            <p>PrivateBin has been configured and the database tables have been created.</p>
            <?php if ($authEnabled): ?>
            <p>Admin account <strong><?php echo htmlspecialchars($adminUser); ?></strong> has been created.</p>
            <?php endif; ?>
            <hr>
            <p class="mb-0"><strong>⚠️ Security:</strong> Delete the entire <code>install/</code> folder immediately!</p>
        </div>
        <a href="../" class="btn btn-primary w-100">Open PrivateBin</a>
    </div>

<?php else: ?>

    <?php if ($error): ?>
    <div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div>
    <?php endif; ?>

    <form method="post" autocomplete="off">
        <input type="hidden" name="step" value="2">

        <div class="form-section">
            <h5>📋 General Settings</h5>
            <div class="mb-3">
                <label for="site_name" class="form-label">Site Name</label>
                <input type="text" class="form-control" id="site_name" name="site_name"
                    value="<?php echo htmlspecialchars($_POST['site_name'] ?? 'PrivateBin'); ?>">
            </div>
        </div>

        <div class="form-section">
            <h5>🗄️ Database Configuration</h5>
            <div class="mb-3">
                <label for="db_type" class="form-label">Database Type</label>
                <select class="form-select" id="db_type" name="db_type" onchange="toggleDbFields()">
                    <option value="sqlite" <?php echo ($_POST['db_type'] ?? 'sqlite') === 'sqlite' ? 'selected' : ''; ?>>SQLite (recommended for small instances)</option>
                    <option value="mysql" <?php echo ($_POST['db_type'] ?? '') === 'mysql' ? 'selected' : ''; ?>>MySQL / MariaDB</option>
                    <option value="pgsql" <?php echo ($_POST['db_type'] ?? '') === 'pgsql' ? 'selected' : ''; ?>>PostgreSQL</option>
                </select>
                <div class="form-text">SQLite requires no separate server — a file is created in the <code>data/</code> directory.</div>
            </div>

            <div id="db-server-fields" style="display:none;">
                <div class="row">
                    <div class="col-md-8 mb-3">
                        <label for="db_host" class="form-label">Host</label>
                        <input type="text" class="form-control" id="db_host" name="db_host"
                            value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>">
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="db_port" class="form-label">Port</label>
                        <input type="text" class="form-control" id="db_port" name="db_port"
                            value="<?php echo htmlspecialchars($_POST['db_port'] ?? ''); ?>" placeholder="Default">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="db_name" class="form-label">Database Name</label>
                    <input type="text" class="form-control" id="db_name" name="db_name"
                        value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'privatebin'); ?>">
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="db_user" class="form-label">Username</label>
                        <input type="text" class="form-control" id="db_user" name="db_user"
                            value="<?php echo htmlspecialchars($_POST['db_user'] ?? ''); ?>">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="db_pass" class="form-label">Password</label>
                        <input type="password" class="form-control" id="db_pass" name="db_pass">
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="tbl_prefix" class="form-label">Table Prefix (optional)</label>
                <input type="text" class="form-control" id="tbl_prefix" name="tbl_prefix"
                    value="<?php echo htmlspecialchars($_POST['tbl_prefix'] ?? ''); ?>" placeholder="e.g. pb_">
                <div class="form-text">Useful if sharing a database with other applications.</div>
            </div>
        </div>

        <div class="form-section">
            <h5>🔐 Authentication</h5>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="auth_enabled" name="auth_enabled" value="1"
                    <?php echo !empty($_POST['auth_enabled']) ? 'checked' : ''; ?> onchange="toggleAuthFields()">
                <label class="form-check-label" for="auth_enabled">Enable built-in user authentication</label>
            </div>

            <div id="auth-fields" style="display:none;">
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="require_login_create" name="require_login_create" value="1"
                        <?php echo !empty($_POST['require_login_create']) || !isset($_POST['step']) ? 'checked' : ''; ?>>
                    <label class="form-check-label" for="require_login_create">Require login to create pastes</label>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="require_login_read" name="require_login_read" value="1"
                        <?php echo !empty($_POST['require_login_read']) ? 'checked' : ''; ?>>
                    <label class="form-check-label" for="require_login_read">Require login to read pastes</label>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="allow_registration" name="allow_registration" value="1"
                        <?php echo !empty($_POST['allow_registration']) ? 'checked' : ''; ?>>
                    <label class="form-check-label" for="allow_registration">Allow self-registration</label>
                </div>

                <hr>
                <h6>Admin Account</h6>
                <div class="mb-3">
                    <label for="admin_username" class="form-label">Admin Username</label>
                    <input type="text" class="form-control" id="admin_username" name="admin_username"
                        value="<?php echo htmlspecialchars($_POST['admin_username'] ?? 'admin'); ?>" autocomplete="off">
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="admin_password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="admin_password" name="admin_password" autocomplete="new-password">
                        <div class="form-text">Minimum 8 characters</div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="admin_password2" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="admin_password2" name="admin_password2" autocomplete="new-password">
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg w-100">Install PrivateBin</button>
    </form>

    <script>
    function toggleDbFields() {
        var type = document.getElementById('db_type').value;
        document.getElementById('db-server-fields').style.display = type === 'sqlite' ? 'none' : 'block';
    }
    function toggleAuthFields() {
        var enabled = document.getElementById('auth_enabled').checked;
        document.getElementById('auth-fields').style.display = enabled ? 'block' : 'none';
    }
    toggleDbFields();
    toggleAuthFields();
    </script>
<?php endif; ?>
</div>
</body>
</html>
