name: Refresh PHP 8 branch

on:
  push:
    branches: [ master ]    
  schedule:
      - cron: '42 2 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout php8 branch 
        uses: actions/checkout@v2
        with:
          # directly checkout the php8 branch
          ref: php8
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 0

      - name: Merge master changes into php8
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge origin/master

      - name: Push new changes
        uses: github-actions-x/commit@v2.8
        with:
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'php8'

